repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: hatch run ruff check .
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: hatch run mypy src
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: hatch run pytest
        language: system
        pass_filenames: false
